# Helm template â€“ ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:8001"
  PAYMENT_SERVICE_URL: "http://payment-service:8002"
  NODE_ENV: "production"
